PR following up on OpenWrt/LEDE build failures (#409)
* Fix 'unknown type' build failures

Issues related to crosscompiling for openwrt.

On OpenWrt/LEDE the build fails due to unknown types:

make[6]: Entering directory '/home/sk/tmp/lede/build_dir/target-mips_24kc_musl/chan-sccp-b-asterisk13/chan-sccp-b-v4.3.0-20170811/src/pbx_impl'
  CC       pbx_impl.lo
In file included from ../../src/common.h:43:0,
                 from pbx_impl.c:15:
../../src/define.h:181:9: error: unknown type name 'pthread_mutex_t'
         pthread_mutex_t mutex;
         ^
../../src/define.h:187:9: error: unknown type name 'pthread_rwlock_t'
         pthread_rwlock_t lock;
         ^
In file included from ../../src/common.h:45:0,
                 from pbx_impl.c:15:
../../src/sccp_enum.h:44:49: error: unknown type name 'uint'
 SCCP_API int SCCP_CALL sccp_channelstate_exists(uint sccp_channelstate_int_value);
                                                 ^

<snip>

In file included from ../../src/common.h:49:0,
                 from pbx_impl.c:15:
../../src/sccp_globals.h:60:2: error: unknown type name 'pthread_t'
  pthread_t socket_thread;          /*!< Socket Thread */
  ^
../../src/sccp_globals.h:61:2: error: unknown type name 'pthread_t'
  pthread_t mwiMonitorThread;          /*!< MWI Monitor Thread */
  ^
../../src/sccp_globals.h:70:2: error: unknown type name 'time_t'
  time_t externexpire;           /*!< External Expire */
  ^
make[6]: *** [Makefile:565: pbx_impl.lo] Error 1

Fix that by including the appropriate headers.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

* Fix build failures due to use of unsafe functions

Currently build on OpenWrt/LEDE fails because functions are used that
are defined as unsafe:

  CC       libsccp_la-sccp_config.lo
sccp_config.c: In function 'sccp_config_parse_jbflags_impl':
sccp_config.c:1338:11: error: use sccp copy string instead of_strcpy
  char * value = strdupa(v->value);
           ^
sccp_config.c:1338:34: error: expected expression before ';' token
  char * value = strdupa(v->value);
                                  ^
sccp_config.c: In function 'sccp_config_parse_webdir':
sccp_config.c:1354:11: error: use sccp copy string instead of_strcpy
  char *value = strdupa(v->value);
           ^
sccp_config.c:1354:33: error: expected expression before ';' token
  char *value = strdupa(v->value);
                                 ^
make[6]: *** [Makefile:884: libsccp_la-sccp_config.lo] Error 1
                                                    ^

Fix this by using the appropriate replacement.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>