Fix build failures due to use of unsafe functions
Currently build on OpenWrt/LEDE fails because functions are used that
are defined as unsafe:

  CC       libsccp_la-sccp_config.lo
sccp_config.c: In function 'sccp_config_parse_jbflags_impl':
sccp_config.c:1338:11: error: use sccp copy string instead of_strcpy
  char * value = strdupa(v->value);
           ^
sccp_config.c:1338:34: error: expected expression before ';' token
  char * value = strdupa(v->value);
                                  ^
sccp_config.c: In function 'sccp_config_parse_webdir':
sccp_config.c:1354:11: error: use sccp copy string instead of_strcpy
  char *value = strdupa(v->value);
           ^
sccp_config.c:1354:33: error: expected expression before ';' token
  char *value = strdupa(v->value);
                                 ^
make[6]: *** [Makefile:884: libsccp_la-sccp_config.lo] Error 1
                                                    ^

Fix this by using the appropriate replacement.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>